/**
 * Constants cơ bản cho hệ thống phân quyền
 * Chỉ chứa constants, logic phân quyền được chuyển sang database
 */

// Định nghĩa các roles trong hệ thống
const ROLES = {
  ADMIN: 'ADMIN',
  XNK: 'XNK', 
  CSKH: 'CSKH',
  FK: 'FK'
};

// Định nghĩa các permissions cơ bản
const PERMISSIONS = {
  VIEW: 'view',
  EDIT: 'edit', 
  DELETE: 'delete'
};

// Định nghĩa các resources trong hệ thống
const RESOURCES = {
  ADMINISTRATOR_ACCESS: 'administrator_access',
  USER_MANAGEMENT: 'user_management',
  CONTENT_MANAGEMENT: 'content_management',
  FINANCIAL_MANAGEMENT: 'financial_management',
  REPORTING: 'reporting',
  PAYROLL: 'payroll',
  DISPUTES_MANAGEMENT: 'disputes_management',
  API_CONTROLS: 'api_controls',
  DATABASE_MANAGEMENT: 'database_management',
  REPOSITORY_MANAGEMENT: 'repository_management',
  SCHEDULES: 'schedules',
  USERS: 'users',
  TASKS: 'tasks',
  SEATS: 'seats',
  NOTIFICATIONS: 'notifications',
  REPORTS: 'reports',
  SYSTEM: 'system'
};

// Định nghĩa quyền cho từng role
const ROLE_PERMISSIONS = {
  ADMIN: {
    [RESOURCES.ADMINISTRATOR_ACCESS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.USER_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.CONTENT_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.FINANCIAL_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.REPORTING]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.PAYROLL]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.DISPUTES_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.API_CONTROLS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.DATABASE_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.REPOSITORY_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.SCHEDULES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.USERS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.TASKS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.SEATS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.NOTIFICATIONS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.REPORTS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.SYSTEM]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE]
  },
  XNK: {
    [RESOURCES.USER_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.CONTENT_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.FINANCIAL_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.REPORTING]: [PERMISSIONS.VIEW],
    [RESOURCES.SCHEDULES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.TASKS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.SEATS]: [PERMISSIONS.VIEW],
    [RESOURCES.NOTIFICATIONS]: [PERMISSIONS.VIEW],
    [RESOURCES.REPORTS]: [PERMISSIONS.VIEW]
  },
  CSKH: {
    [RESOURCES.USER_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.CONTENT_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.DISPUTES_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.REPORTING]: [PERMISSIONS.VIEW],
    [RESOURCES.SCHEDULES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.TASKS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.SEATS]: [PERMISSIONS.VIEW],
    [RESOURCES.NOTIFICATIONS]: [PERMISSIONS.VIEW],
    [RESOURCES.REPORTS]: [PERMISSIONS.VIEW]
  },
  FK: {
    [RESOURCES.FINANCIAL_MANAGEMENT]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.PAYROLL]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [RESOURCES.REPORTING]: [PERMISSIONS.VIEW],
    [RESOURCES.SCHEDULES]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.TASKS]: [PERMISSIONS.VIEW, PERMISSIONS.EDIT],
    [RESOURCES.SEATS]: [PERMISSIONS.VIEW],
    [RESOURCES.NOTIFICATIONS]: [PERMISSIONS.VIEW],
    [RESOURCES.REPORTS]: [PERMISSIONS.VIEW]
  }
};

/**
 * Kiểm tra role có hợp lệ hay không (chỉ check format)
 * @param {string} role - Role cần kiểm tra
 * @returns {boolean}
 */
function isValidRole(role) {
  return Object.values(ROLES).includes(role);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  RESOURCES,
  ROLE_PERMISSIONS,
  isValidRole
};
